<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true" CodeFile="AdminHome.aspx.cs" Inherits="AdminHome" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1>Welcome Admin !</h1>
    <div>
        <asp:GridView ID="mydatagrid" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" ShowFooter="True">
            <Columns>
                <asp:BoundField DataField="EMP_ID" HeaderText="EMP_ID" SortExpression="EMP_ID" />
                <asp:BoundField DataField="EMP_DEPT" HeaderText="EMP_DEPT" SortExpression="EMP_DEPT" />
                <asp:BoundField DataField="EMP_NAME" HeaderText="EMP_NAME" SortExpression="EMP_NAME" />
                <asp:BoundField DataField="EMP_DATEOF_JOINING" HeaderText="EMP_DATEOF_JOINING" SortExpression="EMP_DATEOF_JOINING" />
                <asp:BoundField DataField="EMP_POSITION" HeaderText="EMP_POSITION" SortExpression="EMP_POSITION" />
                <asp:TemplateField HeaderText="EMP_USERNAME" SortExpression="EMP_USERNAME">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("EMP_USERNAME") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="EMP_PASSWORD" HeaderText="EMP_PASSWORD" SortExpression="EMP_PASSWORD" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyDatabaseConnectionString1 %>" SelectCommand="SELECT * FROM [EMPLOYEE_DB]"></asp:SqlDataSource>
    </div>

    
</asp:Content>

